import { Attendee, Competence, Course, Location } from './types/types';

// MARK: Attendees

export const mockAttendee: Attendee[] = [
  {
    $type: 'instructor',
    id: '9b3b6d94-2628-4e25-8948-1184671d255f',
    role: 'Instructor',
    firstName: 'Dillan',
    lastName: 'Feest',
    email: 'isom_hayes28@hotmail.com',
    phoneNumber: null,
    rowVersion: 'AAAAAAAA4pM=',
    competences: [],
  },
  {
    $type: 'student',
    id: '0fea4f1c-82c5-4df6-96d9-9007856dfbd8',
    role: 'Student',
    firstName: 'Marty',
    lastName: 'Hilpert',
    email: 'myrtle77@hotmail.com',
    phoneNumber: null,
    rowVersion: 'AAAAAAABAdQ=',
  },
  {
    $type: 'instructor',
    id: '14a7e8ed-5272-48b2-a5e8-12fca478806e',
    role: 'Instructor',
    firstName: 'Amie',
    lastName: 'Stamm',
    email: 'mikel.emmerich79@gmail.com',
    phoneNumber: null,
    rowVersion: 'AAAAAAAA4pI=',
    competences: [],
  },
  {
    $type: 'instructor',
    id: '1d4c9cfe-764e-4284-84b5-2c634fe98418',
    role: 'Instructor',
    firstName: 'Newell',
    lastName: 'Wisoky',
    email: 'reanna91@yahoo.com',
    phoneNumber: null,
    rowVersion: 'AAAAAAAA4pE=',
    competences: [],
  },
  {
    $type: 'instructor',
    id: '1893a9e5-b8da-4235-a67d-5fa0be9e49a4',
    role: 'Instructor',
    firstName: 'Kenneth',
    lastName: 'Kerluke',
    email: 'kennedy51@hotmail.com',
    phoneNumber: null,
    rowVersion: 'AAAAAAAA4pY=',
    competences: [],
  },
  {
    $type: 'instructor',
    id: '24753bef-3bf7-4b57-82fa-caedbfe73137',
    role: 'Instructor',
    firstName: 'Tess',
    lastName: 'Hintz',
    email: 'chelsey.kreiger@gmail.com',
    phoneNumber: null,
    rowVersion: 'AAAAAAAA4pQ=',
    competences: [],
  },
  {
    $type: 'instructor',
    id: '1c51c405-5a93-4af1-8570-fdf81cbff00c',
    role: 'Instructor',
    firstName: 'Orlo',
    lastName: 'Halvorson',
    email: 'karolann_ohara35@gmail.com',
    phoneNumber: null,
    rowVersion: 'AAAAAAAA4pU=',
    competences: [],
  },
  {
    $type: 'student',
    id: '1c127140-55c9-4f8d-81f7-08996091b218',
    role: 'Student',
    firstName: 'Antonio',
    lastName: "O'Kon",
    email: 'sofia43@yahoo.com',
    phoneNumber: null,
    rowVersion: 'AAAAAAABAdc=',
  },
  {
    $type: 'student',
    id: '441f20dc-4a64-4bf1-8396-08eabd2ff86d',
    role: 'Student',
    firstName: 'Lempi',
    lastName: 'Luettgen',
    email: 'terrill35@yahoo.com',
    phoneNumber: null,
    rowVersion: 'AAAAAAABAd4=',
  },
  {
    $type: 'student',
    id: '1a7213b6-4ae6-48b2-8664-2a02fe868bd0',
    role: 'Student',
    firstName: 'Nathen',
    lastName: 'Nolan',
    email: 'roscoe_dubuque@hotmail.com',
    phoneNumber: null,
    rowVersion: 'AAAAAAABAdE=',
  },
  {
    $type: 'student',
    id: '830107a0-8339-4a7b-a78c-4fd378440784',
    role: 'Student',
    firstName: 'Cecilia',
    lastName: 'Hackett',
    email: 'yolanda_gislason@yahoo.com',
    phoneNumber: null,
    rowVersion: 'AAAAAAABAds=',
  },
  {
    $type: 'student',
    id: '0c2ec14e-3e80-499e-a1c0-684e4acd1079',
    role: 'Student',
    firstName: 'Sydnie',
    lastName: 'Halvorson',
    email: 'enid_mertz@yahoo.com',
    phoneNumber: null,
    rowVersion: 'AAAAAAABAdw=',
  },
  {
    $type: 'student',
    id: 'ecd435df-f583-4a23-b6ba-7edace8102c3',
    role: 'Student',
    firstName: 'Adela',
    lastName: 'Murphy',
    email: 'kristoffer.dare77@hotmail.com',
    phoneNumber: null,
    rowVersion: 'AAAAAAABAdI=',
  },
  {
    $type: 'student',
    id: 'fafd402d-d33d-45ef-b9a1-7f462405d4c4',
    role: 'Student',
    firstName: 'Gordon',
    lastName: 'Berge',
    email: 'michele58@gmail.com',
    phoneNumber: null,
    rowVersion: 'AAAAAAABAdo=',
  },
  {
    $type: 'student',
    id: 'e1a5a5d3-3deb-4372-af57-8559ac15b44c',
    role: 'Student',
    firstName: 'Daphnee',
    lastName: 'Witting',
    email: 'rosario_kessler79@hotmail.com',
    phoneNumber: null,
    rowVersion: 'AAAAAAABAdM=',
  },
  {
    $type: 'student',
    id: 'e0f6b7b1-aa76-403b-b54a-8716ae24e1c5',
    role: 'Student',
    firstName: 'Filomena',
    lastName: 'Mueller',
    email: 'paolo55@gmail.com',
    phoneNumber: null,
    rowVersion: 'AAAAAAABAdk=',
  },
  {
    $type: 'student',
    id: '374b84a7-f176-4ec5-a3e4-9c11271b0ea5',
    role: 'Student',
    firstName: 'Amir',
    lastName: 'Schaden',
    email: 'winnifred.hoeger31@yahoo.com',
    phoneNumber: null,
    rowVersion: 'AAAAAAABAdU=',
  },
  {
    $type: 'student',
    id: '5c06bf81-5466-4b86-bd6c-ad304112c029',
    role: 'Student',
    firstName: 'Maude',
    lastName: 'Oberbrunner',
    email: 'etha_greenfelder@yahoo.com',
    phoneNumber: null,
    rowVersion: 'AAAAAAABAdY=',
  },
  {
    $type: 'student',
    id: '328867cb-af11-42db-a1f9-c5d9d8b34fc3',
    role: 'Student',
    firstName: 'Leif',
    lastName: 'Dicki',
    email: 'kelsie.skiles@hotmail.com',
    phoneNumber: null,
    rowVersion: 'AAAAAAABAd0=',
  },
  {
    $type: 'student',
    id: 'f53dc07c-e1d2-48c1-be9f-e74b4fb2d965',
    role: 'Student',
    firstName: 'Leonor',
    lastName: 'Mohr',
    email: 'bella.grant@gmail.com',
    phoneNumber: null,
    rowVersion: 'AAAAAAABAdg=',
  },
];

// MARK: Locations

export const mockLocation: Location[] = [
  {
    id: '99235b0a-a6fe-4a25-85fa-b39051342540',
    locationName: 'Bednarville',
    rowVersion: 'AAAAAAAA4po=',
  },
  {
    id: '2f31d9c4-12e9-42ad-80fc-ffe9885bc420',
    locationName: 'South Clementina',
    rowVersion: 'AAAAAAAA4pk=',
  },
  {
    id: '1289fa54-3bd1-4161-aeff-de284d43946b',
    locationName: 'Albany',
    rowVersion: 'AAAAAAAA4pg=',
  },
  {
    id: '61ee0866-0d06-48f5-bf75-165342811fb9',
    locationName: 'South Laurelville',
    rowVersion: 'AAAAAAAA4pc=',
  },
];

// MARK: Competences

export const mockCompetence: Competence[] = [
  {
    id: '112c6b46-a187-49a2-a6fe-00bf5ce3ff1c',
    name: 'Configuration',
    rowVersion: 'AAAAAAAA4p8=',
    instructors: [],
  },
  {
    id: '30026ed1-74d4-4690-bc32-29aff7d290fb',
    name: 'Accountability',
    rowVersion: 'AAAAAAAA4qE=',
    instructors: [],
  },
  {
    id: '464a683b-acbe-4e2c-9197-4c71722c43b8',
    name: 'Accounts',
    rowVersion: 'AAAAAAAA4qM=',
    instructors: [],
  },
  {
    id: '5ed56e38-d111-4732-84a7-55c415e778b2',
    name: 'Functionality',
    rowVersion: 'AAAAAAAA4p4=',
    instructors: [],
  },
  {
    id: '3432c1a5-f437-4554-a3b7-5bbace30d20d',
    name: 'Communications',
    rowVersion: 'AAAAAAAA4p0=',
    instructors: [],
  },
  {
    id: '9173b001-940b-4283-8d3e-7db435d8827b',
    name: 'Program',
    rowVersion: 'AAAAAAAA4qI=',
    instructors: [],
  },
  {
    id: 'd517c106-19ec-42ff-b4f4-c3c1223889db',
    name: 'Tactics',
    rowVersion: 'AAAAAAAA4pw=',
    instructors: [],
  },
  {
    id: 'e43297e5-665a-4e92-8268-c44bb966449f',
    name: 'Solutions',
    rowVersion: 'AAAAAAAA4qA=',
    instructors: [],
  },
  {
    id: 'eeb03a93-b1b1-4711-bea8-eb0eb46d6ea1',
    name: 'Usability',
    rowVersion: 'AAAAAAAA4ps=',
    instructors: [],
  },
];

// MARK: Courses

export const mockCourse: Course[] = [
  {
    id: 'd75f5fba-f010-4810-850e-ad3847500216',
    courseCode: 'C++FDJ-040',
    courseType: 'FDJ',
    courseTypeName: 'Försdjupningskurs',
    courseName: 'C++',
    courseDescription:
      'A course in Product with focus on repurpose 24/7 schemas.',
    rowVersion: 'AAAAAAAAw1I=',
  },
  {
    id: 'ef1fe692-88e0-40fa-aba7-a315438af148',
    courseCode: 'C++FDJ-030',
    courseType: 'FDJ',
    courseTypeName: 'Försdjupningskurs',
    courseName: 'C++',
    courseDescription:
      'A course in Internal with focus on extend strategic mindshare.',
    rowVersion: 'AAAAAAAAw1E=',
  },
  {
    id: 'cde6ab69-618e-410c-871a-1cd990f9d480',
    courseCode: 'C++FDJ-020',
    courseType: 'FDJ',
    courseTypeName: 'Försdjupningskurs',
    courseName: 'C++',
    courseDescription:
      'A course in Customer with focus on repurpose open-source mindshare.',
    rowVersion: 'AAAAAAAApBU=',
  },
  {
    id: 'f1bafde2-7340-4230-997c-9a9445b9ee68',
    courseCode: 'C++FDJ-010',
    courseType: 'FDJ',
    courseTypeName: 'Försdjupningskurs',
    courseName: 'C++',
    courseDescription:
      'A course in Internal with focus on enable compelling e-services.',
    rowVersion: 'AAAAAAAApBQ=',
  },
  {
    id: '6b0d693a-f48d-4896-9a06-c677780cb976',
    courseCode: 'C++GRD-020',
    courseType: 'GRD',
    courseTypeName: 'Grundkurs',
    courseName: 'C++',
    courseDescription: 'Yes plx',
    rowVersion: 'AAAAAAAApBM=',
  },
  {
    id: 'a1aa39fd-ebdb-4be3-9865-549936306ab2',
    courseCode: 'MTHGRD-030',
    courseType: 'GRD',
    courseTypeName: 'Grundkurs',
    courseName: 'Math',
    courseDescription:
      'A course in Central with focus on e-enable back-end bandwidth.',
    rowVersion: 'AAAAAAAApBI=',
  },
  {
    id: 'f23b39e1-c16c-4bce-b255-e20ab1dfd096',
    courseCode: 'MTHGRD-020',
    courseType: 'GRD',
    courseTypeName: 'Grundkurs',
    courseName: 'Math',
    courseDescription:
      'A course in Investor with focus on harness front-end deliverables.',
    rowVersion: 'AAAAAAAApBE=',
  },
  {
    id: '9f8fb5fe-f7ca-4a56-8e54-2a0d1961e8dd',
    courseCode: 'MTHGRD-010',
    courseType: 'GRD',
    courseTypeName: 'Grundkurs',
    courseName: 'Math',
    courseDescription:
      'A course in Regional with focus on incentivize interactive action-items.',
    rowVersion: 'AAAAAAAAhNE=',
  },
  {
    id: 'f113b077-f270-4c7f-a922-6ae0130e98f9',
    courseCode: 'C++GRD-010',
    courseType: 'GRD',
    courseTypeName: 'Grundkurs',
    courseName: 'C++',
    courseDescription:
      'A course in Central with focus on syndicate innovative eyeballs.',
    rowVersion: 'AAAAAAAAZZI=',
  },
  {
    id: '169816bc-945d-44bb-9a0a-ef03e800cc63',
    courseCode: 'C#_GRD-010',
    courseType: 'GRD',
    courseTypeName: 'Grundkurs',
    courseName: 'C#',
    courseDescription:
      'A course in Future with focus on generate virtual markets.',
    rowVersion: 'AAAAAAAAZZE=',
  },
  {
    id: 'ec523624-0839-4c69-ad9a-558c75422229',
    courseCode: 'C__GRD-010',
    courseType: 'GRD',
    courseTypeName: 'Grundkurs',
    courseName: 'C#',
    courseDescription:
      'A course in Investor with focus on transform one-to-one mindshare.',
    rowVersion: 'AAAAAAAARlY=',
  },
  {
    id: '3439f120-8253-4d66-a906-5165a8cb1c7e',
    courseCode: 'MRKGRD-020',
    courseType: 'GRD',
    courseTypeName: 'Grundkurs',
    courseName: 'Marketing',
    courseDescription:
      'A course in Legacy with focus on enable best-of-breed infomediaries.',
    rowVersion: 'AAAAAAAARlU=',
  },
  {
    id: '44cd60a7-30a4-47dd-82f3-7e86d6ea29b7',
    courseCode: 'MRKGRD-010',
    courseType: 'GRD',
    courseTypeName: 'Grundkurs',
    courseName: 'Marketing',
    courseDescription:
      'A course in Internal with focus on deliver extensible e-tailers.',
    rowVersion: 'AAAAAAAARlQ=',
  },
  {
    id: 'b5c11557-48cd-4867-bbf2-6bd125b0ab53',
    courseCode: 'MTTGRD-040',
    courseType: 'GRD',
    courseTypeName: 'Grundkurs',
    courseName: 'Matte',
    courseDescription:
      'A course in Global with focus on morph compelling action-items.',
    rowVersion: 'AAAAAAAARlM=',
  },
  {
    id: 'a53d3086-9a67-44eb-982d-1506c8c24f4c',
    courseCode: 'MTTGRD-030',
    courseType: 'GRD',
    courseTypeName: 'Grundkurs',
    courseName: 'Matte',
    courseDescription:
      'A course in Dynamic with focus on strategize frictionless networks.',
    rowVersion: 'AAAAAAAARlI=',
  },
  {
    id: 'c7d56fbd-8943-40ea-87c2-245c139612e3',
    courseCode: 'MTTGRD-020',
    courseType: 'GRD',
    courseTypeName: 'Grundkurs',
    courseName: 'Matte',
    courseDescription:
      'A course in Forward with focus on transform proactive partnerships.',
    rowVersion: 'AAAAAAAARlE=',
  },
  {
    id: '88b46450-6f21-4003-b20b-eb4eb2799c32',
    courseCode: 'MTTGRD-010',
    courseType: 'GRD',
    courseTypeName: 'Grundkurs',
    courseName: 'Matte',
    courseDescription:
      'A course in Dynamic with focus on incubate proactive e-markets.',
    rowVersion: 'AAAAAAAAJxI=',
  },
  {
    id: 'd43075c4-a214-47a7-8ed1-5f2a6f0f36e8',
    courseCode: 'DTAGRD-010',
    courseType: 'GRD',
    courseTypeName: 'Grundkurs',
    courseName: 'Data',
    courseDescription:
      'A course in Dynamic with focus on enhance enterprise e-tailers.',
    rowVersion: 'AAAAAAAAJxE=',
  },
  {
    id: 'd51446ac-afd0-4749-bc17-bb38c6c92ba0',
    courseCode: 'INFGRD-010',
    courseType: 'GRD',
    courseTypeName: 'Grundkurs',
    courseName: 'Infrastructure',
    courseDescription:
      'A course in Principal with focus on strategize magnetic portals.',
    rowVersion: 'AAAAAAAAB9M=',
  },
  {
    id: 'c80b7488-5e62-4a30-b1c9-eb8a44d6ae97',
    courseCode: 'PRGGRD-010',
    courseType: 'GRD',
    courseTypeName: 'Grundkurs',
    courseName: 'Program',
    courseDescription:
      'A course in National with focus on reintermediate user-centric users.',
    rowVersion: 'AAAAAAAAB9E=',
  },
];
